services:
  nginx:
    
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=develpment
      - MONGO_USER=eldho
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev
    
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eldho
      - MONGO_INITDB_ROOT_PASSWORD=mypassword